In [1]:
import pandas as pd
import numpy as np

Step - 1: Load Dataset

In [3]:
df = pd.read_csv(r"C:\\Users\\cheta\\Desktop\\Customer-Data-Wrangling\\data\\raw\\marketing_campaign.csv", sep='\t')

df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

Step - 2 : Understanding structure, columns, and data types

In [4]:
df.info()
df.describe()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')

Step - 3 : Checking missing values, duplicates, and inconsistencies

In [5]:
# Missing values
df.isnull().sum()

# Missing values
df.isnull().sum()

# Duplicates
df.duplicated().sum()

# Unique values in key columns
df['Marital_Status'].unique()
df['Education'].unique()

array(['Graduation', 'PhD', 'Master', 'Basic', '2n Cycle'], dtype=object)

Step - 4: Data Cleaning

In [6]:
# Fill missing Income values with median
df['Income'].fillna(df['Income'].median(), inplace=True)


# Remove duplicates
df.drop_duplicates(inplace=True)

C:\Users\cheta\AppData\Local\Temp\ipykernel_2620\687125772.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Income'].fillna(df['Income'].median(), inplace=True)

Step - 5: Standardizing Categorical Values

In [7]:
df['Marital_Status'] = df['Marital_Status'].replace({
    'Together': 'Married',
    'Absurd': 'Single',
    'YOLO': 'Single',
    'Divorced': 'Single',
    'Widow': 'Single'
})

Step - 6: Date Formatting

In [9]:
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], dayfirst=True)

Step - 7: Feature Engineering

In [10]:
# Age
df['Age'] = 2026 - df['Year_Birth']

# Total Spending
df['Total_Spending'] = df[['MntWines','MntFruits','MntMeatProducts',
                          'MntFishProducts','MntSweetProducts','MntGoldProds']].sum(axis=1)

# Total Children
df['Children'] = df['Kidhome'] + df['Teenhome']

Step - 7: Dropping Unnecessary Columns

In [11]:
df.drop(['ID'], axis=1, inplace=True)

Step - 8: Save CLeaned Dataset

In [14]:
df.to_csv(r"C:\Users\cheta\Desktop\Customer-Data-Wrangling\data\cleaned\cleaned_data.csv", index=False)

Step - 9: Data Dictionary

In [15]:
data_dict = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.values
})

data_dict

            Column Name       Data Type
0            Year_Birth           int64
1             Education          object
2        Marital_Status          object
3                Income         float64
4               Kidhome           int64
5              Teenhome           int64
6           Dt_Customer  datetime64[ns]
7               Recency           int64
8              MntWines           int64
9             MntFruits           int64
10      MntMeatProducts           int64
11      MntFishProducts           int64
12     MntSweetProducts           int64
13         MntGoldProds           int64
14    NumDealsPurchases           int64
15      NumWebPurchases           int64
16  NumCatalogPurchases           int64
17    NumStorePurchases           int64
18    NumWebVisitsMonth           int64
19         AcceptedCmp3           int64
20         AcceptedCmp4           int64
21         AcceptedCmp5           int64
22         AcceptedCmp1           int64
23         AcceptedCmp2           int64
24             Complain           int64
25        Z_CostContact           int64
26            Z_Revenue           int64
27             Response           int64
28                  Age           int64
29       Total_Spending           int64
30             Children           int64

In [16]:
data_dict = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.values
})

data_dict

            Column Name       Data Type
0            Year_Birth           int64
1             Education          object
2        Marital_Status          object
3                Income         float64
4               Kidhome           int64
5              Teenhome           int64
6           Dt_Customer  datetime64[ns]
7               Recency           int64
8              MntWines           int64
9             MntFruits           int64
10      MntMeatProducts           int64
11      MntFishProducts           int64
12     MntSweetProducts           int64
13         MntGoldProds           int64
14    NumDealsPurchases           int64
15      NumWebPurchases           int64
16  NumCatalogPurchases           int64
17    NumStorePurchases           int64
18    NumWebVisitsMonth           int64
19         AcceptedCmp3           int64
20         AcceptedCmp4           int64
21         AcceptedCmp5           int64
22         AcceptedCmp1           int64
23         AcceptedCmp2           int64
24             Complain           int64
25        Z_CostContact           int64
26            Z_Revenue           int64
27             Response           int64
28                  Age           int64
29       Total_Spending           int64
30             Children           int64

Step - 10: Save the data dictionary

In [21]:
data_dict.to_csv("C:\\Users\\cheta\\Desktop\\Customer-Data-Wrangling\\outputs\\data_dictionary.csv", index=False)